### ISSUE TITLE
[Player] 벽 차기 기능

### ISSUE THREAD

**Issue by Hinnlang** [Gongju-Unity-Bootcamp/HANDSOMEDINO#11]
# 설명
플랫폼의 왼쪽 혹은 오른쪽 벽에 접촉했을 때, 키보드 'a'를 누르면 대각선 위 방향으로 이동한다.
player가 벽에 접촉했을 때, 천천히 떨어지도록 한다.
Raycast를 이용해서 player의 일정 범위 내에 벽이 들어오면 감지할 수 있도록 한다.

# 참고자료
- [Youtube 벽타기 레퍼런스: 마리오](https://www.youtube.com/watch?v=Iu8V_CZNo9g)
- [Youtube 벽타기 script](https://www.youtube.com/watch?v=43gE0TabDMo)

# 주의사항
기본 점프와 동일하게 작용하되, 점프 방향만 변화 시키도록 코드를 짠다.

**Comment by JJARSANGKIM** [comment]
![image](https://github.com/Gongju-Unity-Bootcamp/HANDSOMEDINO/assets/102023674/6674a0e5-fcfb-4c0e-9281-255408f8d7c7)

벽에 붙다가 반대편으로 점프시 기존 점프 모션과 이어짐
