### ISSUE TITLE
[Camera] Follow 기능

### ISSUE THREAD

**Issue by Hinnlang** [Gongju-Unity-Bootcamp/HANDSOMEDINO#12]
# 설명
main camera가 보여주는 영역을 지정한다.

# 참고자료
관련된 기획서 혹은 이슈 등의 링크를 답니다.
- [Youtube : How to Make Camera Follow In UNITY 2D](https://www.youtube.com/watch?v=FXqwunFQuao)
- [Youtube: Unity 2D SMOOTH CAMERA FOLLOW Tutorial | Unity 2D Platformer Tutorial #3](https://www.youtube.com/watch?v=QfLhSzeZaoA)

# 주의사항
camera가 맵 외부를 비추지 않도록 한다.
player가 camera의 중앙을 넘어서서 이동하면 player의 움직임에 따라 함께 이동한다.

**Comment by JJARSANGKIM** [comment]
https://velog.io/@cedongne/Unity-2D-%EC%B9%B4%EB%A9%94%EB%9D%BC-%EB%B2%94%EC%9C%84-%EC%A0%9C%ED%95%9C%ED%95%98%EA%B8%B0

카메라 범위 제한
