### ISSUE TITLE
[Bug] Test

### ISSUE THREAD

**Issue by JJARSANGKIM** [Gongju-Unity-Bootcamp/HANDSOMEDINO#2]
# 테스트 환경
테스트를 진행한 환경을 알려주세요.
- OS :
- CPU :
- GPU :
- Mode : Editor | Standalone(Win) | Standalone(Mac)

# 설명
어떤 버그가 생기는지 설명해주세요.

# 재현하기
버그 발생 상황을 단계별로 설명해주세요.
1. 
2.
3.

# 스크린샷
버그가 발생한 화면을 캡쳐하여 알려주세요. (동영상 가능)

**Comment by Hinnlang** [comment]
테스트
