### ISSUE TITLE
[Player] prototype map

### ISSUE THREAD

**Issue by Hinnlang** [Gongju-Unity-Bootcamp/HANDSOMEDINO#8]
# 설명
플레이어의 기능을 test 해볼 수 있는 prototype map을 만든다.

# 참고자료

# 주의사항

**Comment by JJARSANGKIM** [comment]
![image](https://github.com/Gongju-Unity-Bootcamp/HANDSOMEDINO/assets/102023674/3c5da4fe-cb4d-4480-9ec4-60e2c236bd73)
