### ISSUE TITLE
[Player] jump 기능

### ISSUE THREAD

**Issue by Hinnlang** [Gongju-Unity-Bootcamp/HANDSOMEDINO#9]
# 설명
키보드 입력 값 'a'를 누르면 rigidbody2D가 적용된 player가 +y축 방향으로 상승했다가 중력의 영향을 받아 떨어진다.
player의 이동 방향에 영향을 받는다.
space 키가 눌려진 시간에 따라 점프의 크기가 변한다.
physic material2D에서 bounceness를 조절해서 튕김을 구현한다. 

# 참고자료
- [Unity manual: rigidbody2D](https://docs.unity3d.com/kr/2021.3/Manual/class-Rigidbody2D.html) 
- [Unity scripting api: rigidbody2D](https://docs.unity3d.com/ScriptReference/Rigidbody2D.html) 
- [Youtube Unity 2D basic 플랫포머 플레이어 이동, 점프](https://www.youtube.com/watch?v=RmqWuoFHD5g)

# 주의사항
점프의 크기를 나타내는 변수 jumpPower의 값은 플랫폼 사이에서 움직일 정도로만 설정한다.
한 번 점프 후 플랫폼에 닿기 전까지 기본 최대 점프 횟수를 1회로 제한한다.

**Comment by JJARSANGKIM** [comment]
![image](https://github.com/Gongju-Unity-Bootcamp/HANDSOMEDINO/assets/102023674/0fca483e-6c4e-49da-b7eb-cbf3818d5e9d)
